// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjcpsitegufprrynyisr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqY3BzaXRlZ3VmcHJyeW55aXNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTAyMTYsImV4cCI6MjA2MzkyNjIxNn0.lvPSKMUQAbL_WE1T7xj2Of4KXf4XapO_3rw6lJDrt2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);